# Generated by Django 3.0.8 on 2020-07-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=120)),
                ('applicant_skills', models.TextField()),
                ('applicant_wage', models.IntegerField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.JobPosting')),
            ],
        ),
    ]
