# Generated by Django 3.0.8 on 2020-07-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
